---
- hosts: all
  become: yes
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        timeout: 300

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts with all consul nodes
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}{{ hostvars[host]['ansible_host'] }} {{ host }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED CONSUL HOSTS"

    - name: Ensure .ssh directory exists
      file:
        path: /home/ec2-user/.ssh
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0700

    - name: Generate SSH keypair for ec2-user if not present
      become_user: ec2-user
      openssh_keypair:
        path: /home/ec2-user/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
        mode: 0600

    - name: Fetch public key from each node
      slurp:
        src: /home/ec2-user/.ssh/id_rsa.pub
      register: pubkeys
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"
      run_once: true

    - name: Set fact for all public keys
      set_fact:
        all_pubkeys: "{{ pubkeys.results | map(attribute='content') | map('b64decode') | list }}"
      run_once: true

    - name: Distribute all public keys to authorized_keys
      authorized_key:
        user: ec2-user
        key: "{{ item }}"
      loop: "{{ all_pubkeys }}"

    - name: Install unzip
      package:
        name: unzip
        state: present

    - name: Install yum-utils
      package:
        name: yum-utils
        state: present

    - name: Add HashiCorp YUM repository
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

    - name: Clean yum cache after adding HashiCorp repo
      command: yum clean all

    - name: Make yum cache
      command: yum makecache

    - name: Wait for repo propagation
      wait_for:
        timeout: 5

    - name: Install Consul from HashiCorp repo
      package:
        name: consul
        state: present
